version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./nomad-backend:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
      - UNSPLASH_SECRET_KEY=${UNSPLASH_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FLIGHT_API_KEY=${FLIGHT_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload